# Generated by Django 3.2.20 on 2023-07-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20230727_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawrequest',
            old_name='trans_date',
            new_name='request_date',
        ),
        migrations.RemoveField(
            model_name='withdrawrequest',
            name='trans_id',
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='paid_date',
            field=models.DateField(),
        ),
    ]
