# Generated by Django 3.2.20 on 2023-07-27 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_withdrawrequest_paid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawrequest',
            name='paid_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
