# Generated by Django 3.2.20 on 2023-07-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_withdrawrequest_paid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='budget',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='daily_income',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='level1_com',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='level2_com',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='level3_com',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='total_earnings',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='total_withdrawals',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='upgraderequest',
            name='due_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
