# Generated by Django 3.2.20 on 2023-08-01 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20230728_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='last_interest_calculation',
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_interest_calculated',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
